-- creazione tabelle per il corso

drop table employee;

create table employee (
	id int generated by default as IDENTITY,
	id_contratto int,
	country varchar(50) not null,
	email varchar(50) not null,
	fullname varchar(50) not null,
	gender varchar(50) not null,
	address varchar(100),
	primary key (id),
	foreign key (id_contratto) references contratto(id_contratto)
)
delete from employee;

insert into employee (country, email, fullname, gender, address)
	values ('Italy', 'aa@bb.it', 'Marco Letruco', 'mascio', 'via bella luna 10 Milano'),
	 ('Italy', 'bb@vv.it', 'Andrea Depardie', 'mascio', 'Corso Agnelli 12 Torino'),	
	 ('Italy', 'cc@vv.it', 'Paolo Rosso', 'mascio', 'Corso Blue 12 Torino'),	
	 ('Italy', 'vvbb@vv.it', 'Cinzia Verde', 'femina', 'Via Lagrnage 355 Torino'),	
	 ('Italy', 'ssbb@vv.it', 'Gianni Leturco', 'mascio', 'Corso Francia Milano'),	
	 ('Italy', 'tt@vv.it', 'Alice Bianca', 'femina', 'Via suza 1 Torino'),	
	 ('Italy', 'uu@vv.it', 'Giuseppe Lagrande', 'mascio', 'Corso Monte 33 Roma')	
	
select * from employee e 	

drop table contratto;

create table contratto (
	id_contratto int generated by default as IDENTITY,
	id_categoria int,
	id_ruolo int,
	stipendio numeric(10) not null,
	data_assunzione date not null,
	data_dimissione date,
	primary key (id_contratto),
	foreign key (id_categoria) references categoria(id_categoria),
	foreign key (id_ruolo) references ruolo(id_ruolo)
)

delete from contratto;
insert into contratto (stipendio, data_assunzione)
	values (1500, '2025-05-01'),
	(1500, '2025-05-01'),
	(1600, '2025-05-01'),
	(1800, '2025-05-01'),
	(2000, '2025-05-01'),
	(2500, '2025-05-01')

	select * from contratto;
create table categoria (
	id_categoria int generated by default as IDENTITY,
	tipo varchar(100) not null,
	primary key (id_categoria)
)
	

insert into categoria (tipo)
	values ('Impiegato'),('Quadro'),('Dirigente')

select * from categoria;	


create table ruolo (
	id_ruolo int generated by default as IDENTITY,
	stipendio_minimo numeric(10) not null,
	descrizione varchar(100) not null,
	primary key (id_ruolo)
)

insert into ruolo (stipendio_minimo, descrizione)
	values (1000, 'amministrativo'),
		   (1200, 'tecnico'),
		   (1300, 'sviluppatore'),
		   (1800, 'capo progetto'),
		   (2000, 'commerciale')

select * from ruolo;

/*
 * Step 1 creazione view
 */
CREATE or Replace view list_employee as
select e.fullname, e.gender , c.data_assunzione, c.stipendio, cat.tipo, r.descrizione
from employee e 
	left join contratto c 
			on c.id_contratto = e.id_contratto
	left join categoria cat
			on cat.id_categoria = c.id_categoria
	left join ruolo r 
			on r.id_ruolo = c.id_ruolo 

select * from list_employee l 